name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: hackaton
  EKS_CLUSTER_NAME: extravagant-dubstep-hideout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY .
        $(aws ecr get-login --no-include-email --region $AWS_REGION)

    - name: Tag Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Etiqueta única basada en la fecha
        docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Push Docker image to ECR
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' # Solo ejecutar el deploy en un push a main o cuando sea manual

    steps:
    - name: Set up kubectl
      uses: aws-actions/configure-kubeconfig@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cluster-name: ${{ env.EKS_CLUSTER_NAME }}
        region: ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/my-nextjs-app-deployment my-nextjs-app=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        kubectl rollout status deployment/my-nextjs-app-deployment
